# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  securityexample-mysql:
    image: mysql:8.0.30
    volumes:
      - ./config/mysql:/etc/mysql/conf.d
    #   - ~/volumes/jhipster/SecurityExample/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=123456aA@
      - MYSQL_DATABASE=securityexample
      - MYSQL_USER=duongnd21
      - MYSQL_PASSWORD=123456aA@
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
